//! Canonical Astral transcript state that preserves app-server `ThreadItem`
//! values instead of flattening them into renderer-specific text.

mod block;
mod collab_tool;
mod display;
mod dynamic_tool;
mod live_item;
mod markdown;
mod mcp_tool;
mod read_tool;
mod render;
mod search_tool;
mod transcript;
mod verb_group;
mod web_search;

pub use block::ContextCompactionBlock;
pub use block::EntryBlock;
pub use block::ReasoningBlock;
pub use block::ReasoningVisibility;
pub use collab_tool::CollabAgentToolCallBlock;
pub use display::DisplayMode;
pub use display::EntryDisplayState;
pub use dynamic_tool::DynamicToolCallBlock;
pub use live_item::LiveItem;
pub use markdown::CodeLineHighlighter;
pub use markdown::LineJoiner;
pub use markdown::MarkdownLine;
pub use markdown::MarkdownLink;
pub use markdown::MarkdownStyle;
pub use markdown::MarkdownSyntaxTheme;
pub use markdown::MarkdownTable;
pub use markdown::MarkdownTableAlignment;
pub use markdown::highlight_fenced_code;
pub use markdown::render_literal_with_metadata;
pub use markdown::render_markdown;
pub use markdown::render_markdown_with_metadata;
pub use markdown::wrap_styled_line_with_metadata;
pub use mcp_tool::McpToolCallBlock;
pub use render::DiffStyle;
pub use render::EntryRenderOptions;
pub use render::RenderedEntry;
pub use render::render_entry;
pub use render::render_verb_group_header;
pub use transcript::ApplyOutcome;
pub use transcript::EntryLifecycle;
pub use transcript::Transcript;
pub use transcript::TranscriptEntry;
pub use transcript::TranscriptEntryId;
pub use transcript::TranscriptGap;
pub use transcript::TranscriptTurn;
pub use verb_group::VerbGroupDisplayState;
pub use verb_group::VerbGroupProjection;
pub use verb_group::VerbGroupSpan;
pub use verb_group::project_verb_groups;
pub use verb_group::scan_verb_groups;
pub use web_search::WebSearchBlock;
