// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolMode } from "../ToolMode";
import type { ModelCapabilitySource } from "./ModelCapabilitySource";

export type ModelCapabilities = {
/**
 * Effective context window used for this model.
 */
contextWindow: bigint | null,
/**
 * Maximum context window accepted by model-level overrides, when known.
 */
maxContextWindow: bigint | null, maxOutputTokens: bigint | null, toolMode: ToolMode | null, supportsTools: boolean | null, supportsParallelTools: boolean | null, supportsVision: boolean | null, supportsWebSearch: boolean | null, supportsImageGeneration: boolean | null, supportsPromptCache: boolean | null, supportsReasoning: boolean | null, supportsNativeStreaming: boolean | null, supportedEndpoints: Array<string>, sources: Array<ModelCapabilitySource>, };
