// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type ThreadInjectItemsParams = { threadId: string,
/**
 * Raw model history items to append to the thread's model-visible history.
 */
items: Array<JsonValue>, };
