// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication mode for Astral-managed credentials.
 *
 * Astral actively supports API-key auth. Token-backed variants are retained
 * only so legacy payloads can be identified and rejected cleanly.
 */
export type AuthMode = "apikey" | "chatgpt" | "agentIdentity" | "personalAccessToken";
